# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/SonarJetLens/Dev/hyperperf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/SonarJetLens/Dev/hyperperf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/SonarJetLens/Dev/hyperperf/CMakeFiles /Users/SonarJetLens/Dev/hyperperf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/SonarJetLens/Dev/hyperperf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hyperbench

# Build rule for target.
hyperbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyperbench
.PHONY : hyperbench

# fast build rule for target.
hyperbench/fast:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/build
.PHONY : hyperbench/fast

hayai_tests.o: hayai_tests.cpp.o

.PHONY : hayai_tests.o

# target to build an object file
hayai_tests.cpp.o:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/hayai_tests.cpp.o
.PHONY : hayai_tests.cpp.o

hayai_tests.i: hayai_tests.cpp.i

.PHONY : hayai_tests.i

# target to preprocess a source file
hayai_tests.cpp.i:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/hayai_tests.cpp.i
.PHONY : hayai_tests.cpp.i

hayai_tests.s: hayai_tests.cpp.s

.PHONY : hayai_tests.s

# target to generate assembly for a file
hayai_tests.cpp.s:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/hayai_tests.cpp.s
.PHONY : hayai_tests.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/main.cpp.s
.PHONY : main.cpp.s

thread_tests.o: thread_tests.cpp.o

.PHONY : thread_tests.o

# target to build an object file
thread_tests.cpp.o:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/thread_tests.cpp.o
.PHONY : thread_tests.cpp.o

thread_tests.i: thread_tests.cpp.i

.PHONY : thread_tests.i

# target to preprocess a source file
thread_tests.cpp.i:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/thread_tests.cpp.i
.PHONY : thread_tests.cpp.i

thread_tests.s: thread_tests.cpp.s

.PHONY : thread_tests.s

# target to generate assembly for a file
thread_tests.cpp.s:
	$(MAKE) -f CMakeFiles/hyperbench.dir/build.make CMakeFiles/hyperbench.dir/thread_tests.cpp.s
.PHONY : thread_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hyperbench"
	@echo "... hayai_tests.o"
	@echo "... hayai_tests.i"
	@echo "... hayai_tests.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... thread_tests.o"
	@echo "... thread_tests.i"
	@echo "... thread_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

